.PHONY: clean All

All:
	@echo "----------Building project:[ Cliente - Debug ]----------"
	@cd "/home/yordan/Desktop/Proyecto1-SO/Cliente" && "$(MAKE)" -f  "Cliente.mk"
clean:
	@echo "----------Cleaning project:[ Cliente - Debug ]----------"
	@cd "/home/yordan/Desktop/Proyecto1-SO/Cliente" && "$(MAKE)" -f  "Cliente.mk" clean
